### ISSUE TITLE
[FEAT] ContextMenu 추가하기

### ISSUE THREAD

**Issue by isayaksh** [isayaksh/ChromeNewTabCustom#3]
## [ Issue ] ✨ Feature 
마우스 우클릭시 발생하는 ContextMenu를 추가하기

## Description
![image](https://github.com/isayaksh/ChromeNewTabCustom/assets/85926257/a5f4545f-9444-4262-a3b0-e59acd759e60)
- 마우스 우클릭 시 다양한 ContextMenu가 존재한다.
- `ChromeNewTabExtension` 익스텐션을 다운 받을 시, 추가적인 contextMenu가 추가될 수 있도록 기능을 추가한다.

## TODO
- [x] manifest.json 수정하기
- [x] background.js 생성하기
- [x] 우클릭 후 contextmenu 확인하기

**Comment by isayaksh** [comment]
## Feature #3 진행 상황
현재까지 진행된 contextMenu 추가 개발은 다음과 같다.

![image](https://github.com/isayaksh/ChromeNewTabCustom/assets/85926257/e676a568-c3c8-4e1c-ba3c-42b47059a690)

- 마우스 우클릭 시, `Save Page URL` 메뉴가 추가된 것을 확인할 수 있다.

## Next TODO
- [x] `Save Page URL` 메뉴 클릭 시 현재 page URL을 로컬 스토리지에 저장!

**Comment by isayaksh** [comment]
## Feature #3 진행 상황
현재까지 진행된 contextMenu 추가 개발은 다음과 같다.

![스크린샷 2024-04-15 오후 8 13 07](https://github.com/isayaksh/ChromeNewTabCustom/assets/85926257/62fca5d6-af1b-41a7-8357-f148dc64aef5)

- 왼쪽 상단에 흰색 글자로 구성된 데이터는 페이지의 url을 저장한 데이터 내역이다.
- 현재 `chrome.storage.local`에 데이터를 저장한 후 데이터를 `<li>` 형식으로 출력하는데 성공하였다.

## Next TODO
- [x] 저장된 url 정보를 아름답게 출력할 수 있도록 html과 css를 정리한다.

**Comment by isayaksh** [comment]
## Feature #3 진행 상황
이제 거의 모든 기능구현은 완료되었다.

<img width="1920" alt="image" src="https://github.com/isayaksh/ChromeNewTabCustom/assets/85926257/bd158ef4-7b4f-461d-b5b5-8422a7c4da66">


- `block`을 생성하여 url이 추가될때마다 `block` 내부에 해당 url을 저장한 시간과 url 정보를 담아서 화면에 뿌린다.
