### ISSUE TITLE
[FEAT] URL 블록 UI 수정하기

### ISSUE THREAD

**Issue by isayaksh** [isayaksh/ChromeNewTabCustom#5]
## [ Issue ] ✨ Feature 

![image](https://github.com/isayaksh/ChromeNewTabCustom/assets/85926257/468774e0-389a-42f3-bdfe-c3f890f40787)

## Description

현재까지 개발된 기능은 다음과 같다.

- [x] 우측 상단 네비게이션 바에 Google Mail, Google Calendar, Google Drive, Google Docs에 연결할 수 있는 링크
- [x] 구글 검색을 할 수 있는 검색 바
- [x] Context Menu에 `Save page URL` 메뉴 추가
- [x] `Saave page URL` 클릭 시, Chrome Extension  API를 활용하여 현재 페이지의 URL을 보관
- [x] `chrome.storage.local` 보관된 url 리스트를 블록으로 생성하여 HTML로 그리기

## TODO

현재 URL 정보가 담긴 블록의 UI가 마음에 들지 않아서 수정하고자 한다.
더불어, 블록에 `X` 버튼을 추가하여 보관중인 URL 중 필요 없는 URL은 제거하고자 한다.

- [x] URL 정보가 담긴 블록 구성 및 배치 구조 수정하기
- [x] URL 블록을 제거할 수 있는 `X` 버튼 추가하기

**Comment by isayaksh** [comment]
## FEATURE #5

### 🖼 `memo` 블록 UI 수정

<img width="1920" alt="image" src="https://github.com/isayaksh/ChromeNewTabCustom/assets/85926257/04e83f52-ba1d-416c-be29-ff0af18717d9">

- 기존의 저장된 URL 정보를 보관하는 `memo` 블록의 UI를 일부 수정하였다.

### 📄 addEventListener for delete memo block

- 추가로 `memo` 블록에 해당 블록을 삭제할 수 있는 `cancel` 버튼을 추가하여 해당 블록을 삭제할 수 있는 기능을 추가하였다.
- HTML에 존재하는 모든 `.dot-cancel` 엘리먼트를 찾아서 addEventLister를 통해 이벤트를 등록하였다.
- 즉각적으로 `memo` 블록이 사라질 수 있도록 `memo.style.display = 'none';` 를 적용하였다.
- 또한, `chrome.storage.local`에 저장된 데이터가 삭제될 수 있도록 `filter`를 사용하여 해당 요소를 삭제하였다.

```javascript
document.addEventListener('DOMContentLoaded', function() {
    const dotCancel = document.querySelectorAll('.dot-cancel');
    dotCancel.forEach(function(cancelButton) {
        cancelButton.addEventListener('click', function() {
            const memo = cancelButton.closest('.memo'); // .memo 엘리먼트 찾기
            memo.style.display = 'none'; // .memo 엘리먼트 숨기기

            const date = memo.querySelector('.header').textContent;

            console.log('select date : ' + date);

            // 저장된 데이터를 가져와서 삭제할 데이터를 찾고 제거합니다.
            chrome.storage.local.get('urls', (data) => {
                const urls = data.urls;
                // 삭제할 데이터를 찾아서 제거
                const updatedUrls = urls.filter(obj => obj.date !== date);
                // 수정된 데이터를 다시 저장
                chrome.storage.local.set({ 'urls': updatedUrls }, () => {
                    console.log('Data updated successfully.');
                });
            });

        });
    });
});
```
